-- 보여줄 col : 아이스크림의 맛
-- 기준 : 총 주문량 3000초과 and 주 성분이 과일
-- 정렬 : 총 주문량 내림차순
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF LEFT JOIN ICECREAM_INFO 
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;
