-- 성분 타입, 성분 타입에 대한 총 주문량
# SELECT * FROM FIRST_HALF -- 아이스크림 맛별 판매량
# SELECT * FROM ICECREAM_INFO -- 아이스크림 맛별 성분 타입
SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF F, ICECREAM_INFO I
WHERE F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER asc
